/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "scan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ripas_BleEvent, ripas_BleEvent, AUTO)


PB_BIND(ripas_DeviceInfo, ripas_DeviceInfo, AUTO)


PB_BIND(ripas_ScanBatch, ripas_ScanBatch, 2)



