/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_RIPAS_PROTO_SCAN_PB_H_INCLUDED
#define PB_RIPAS_PROTO_SCAN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(6) ripas_BleEvent_mac_t;
typedef PB_BYTES_ARRAY_T(31) ripas_BleEvent_adv_data_t;
typedef struct _ripas_BleEvent {
    ripas_BleEvent_mac_t mac;
    int32_t rssi;
    ripas_BleEvent_adv_data_t adv_data;
    uint64_t utc_ms;
    uint64_t monotonic_ms;
    bool time_sync;
} ripas_BleEvent;

typedef struct _ripas_DeviceInfo {
    pb_callback_t device_id;
    pb_callback_t fw_version;
} ripas_DeviceInfo;

typedef struct _ripas_ScanBatch {
    bool has_device;
    ripas_DeviceInfo device;
    pb_size_t ble_count;
    ripas_BleEvent ble[10];
    uint64_t batch_seq;
} ripas_ScanBatch;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ripas_BleEvent_init_default              {{0, {0}}, 0, {0, {0}}, 0, 0, 0}
#define ripas_DeviceInfo_init_default            {{{NULL}, NULL}, {{NULL}, NULL}}
#define ripas_ScanBatch_init_default             {false, ripas_DeviceInfo_init_default, 0, {ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default, ripas_BleEvent_init_default}, 0}
#define ripas_BleEvent_init_zero                 {{0, {0}}, 0, {0, {0}}, 0, 0, 0}
#define ripas_DeviceInfo_init_zero               {{{NULL}, NULL}, {{NULL}, NULL}}
#define ripas_ScanBatch_init_zero                {false, ripas_DeviceInfo_init_zero, 0, {ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero, ripas_BleEvent_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ripas_BleEvent_mac_tag                   1
#define ripas_BleEvent_rssi_tag                  2
#define ripas_BleEvent_adv_data_tag              3
#define ripas_BleEvent_utc_ms_tag                4
#define ripas_BleEvent_monotonic_ms_tag          5
#define ripas_BleEvent_time_sync_tag             6
#define ripas_DeviceInfo_device_id_tag           1
#define ripas_DeviceInfo_fw_version_tag          2
#define ripas_ScanBatch_device_tag               1
#define ripas_ScanBatch_ble_tag                  2
#define ripas_ScanBatch_batch_seq_tag            3

/* Struct field encoding specification for nanopb */
#define ripas_BleEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    mac,               1) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,              2) \
X(a, STATIC,   SINGULAR, BYTES,    adv_data,          3) \
X(a, STATIC,   SINGULAR, UINT64,   utc_ms,            4) \
X(a, STATIC,   SINGULAR, UINT64,   monotonic_ms,      5) \
X(a, STATIC,   SINGULAR, BOOL,     time_sync,         6)
#define ripas_BleEvent_CALLBACK NULL
#define ripas_BleEvent_DEFAULT NULL

#define ripas_DeviceInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   device_id,         1) \
X(a, CALLBACK, SINGULAR, STRING,   fw_version,        2)
#define ripas_DeviceInfo_CALLBACK pb_default_field_callback
#define ripas_DeviceInfo_DEFAULT NULL

#define ripas_ScanBatch_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device,            1) \
X(a, STATIC,   REPEATED, MESSAGE,  ble,               2) \
X(a, STATIC,   SINGULAR, UINT64,   batch_seq,         3)
#define ripas_ScanBatch_CALLBACK NULL
#define ripas_ScanBatch_DEFAULT NULL
#define ripas_ScanBatch_device_MSGTYPE ripas_DeviceInfo
#define ripas_ScanBatch_ble_MSGTYPE ripas_BleEvent

extern const pb_msgdesc_t ripas_BleEvent_msg;
extern const pb_msgdesc_t ripas_DeviceInfo_msg;
extern const pb_msgdesc_t ripas_ScanBatch_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ripas_BleEvent_fields &ripas_BleEvent_msg
#define ripas_DeviceInfo_fields &ripas_DeviceInfo_msg
#define ripas_ScanBatch_fields &ripas_ScanBatch_msg

/* Maximum encoded size of messages (where known) */
/* ripas_DeviceInfo_size depends on runtime parameters */
/* ripas_ScanBatch_size depends on runtime parameters */
#define RIPAS_PROTO_SCAN_PB_H_MAX_SIZE           ripas_BleEvent_size
#define ripas_BleEvent_size                      71

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
