# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/scan.proto
# Protobuf Python Version: 6.33.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'proto/scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/scan.proto\x12\x05ripas\"p\n\x08\x42leEvent\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x0c\n\x04rssi\x18\x02 \x01(\x11\x12\x10\n\x08\x61\x64v_data\x18\x03 \x01(\x0c\x12\x0e\n\x06utc_ms\x18\x04 \x01(\x04\x12\x14\n\x0cmonotonic_ms\x18\x05 \x01(\x04\x12\x11\n\ttime_sync\x18\x06 \x01(\x08\"3\n\nDeviceInfo\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nfw_version\x18\x02 \x01(\t\"_\n\tScanBatch\x12!\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x11.ripas.DeviceInfo\x12\x1c\n\x03\x62le\x18\x02 \x03(\x0b\x32\x0f.ripas.BleEvent\x12\x11\n\tbatch_seq\x18\x03 \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLEEVENT']._serialized_start=27
  _globals['_BLEEVENT']._serialized_end=139
  _globals['_DEVICEINFO']._serialized_start=141
  _globals['_DEVICEINFO']._serialized_end=192
  _globals['_SCANBATCH']._serialized_start=194
  _globals['_SCANBATCH']._serialized_end=289
# @@protoc_insertion_point(module_scope)
